### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by nayrsirhc**
Changing `discussion` to `discussing`

## Type of change
Documentation

### What should this PR do?
Fix grammar

### Why are we making this change?
To fix a typo

### What are the acceptance criteria? 
Just a documentation change, just needs an approval

### How should this PR be tested?
Only docs so no testing needed

### CODE REVIEW

**Review by smythp — APPROVED** [review]
Nice :+1:

**Comment by smythp** [comment]
Approved, but you should merge in the yaml changes first. :)

**Comment by nayrsirhc** [comment]
You will see me fiddling a bit, trying to get my git signing sorted from my local and using this PR as a testing ground hope you dont mind

**Comment by smythp** [comment]
By all means :construction:

**Comment by smythp** [comment]
Also, if you want to rerun the checker, you can add empty commits and push, you don't need to make small changes to the files.

```
git commit --allow-empty -m "This commit does nothing"
```

Your commits will get squashed on merge so don't worry about committing too much. Best of luck.

**Comment by nayrsirhc** [comment]
Thanks for the tips and patience, didnt think of doing an empty commit will keep that one in the back pocket! Ok looks like I got my sigstore gitsign stuff set up! Was actually really easy, love the idea as well, thanks for all the patience here, looks like its ready to merge now

**Comment by nayrsirhc** [comment]
I just realized my autoformatter changed quite a lot here but its only formatting / removal of whitespace

**Pull request merged**
