### PR TITLE
fix: notices.yaml

### PR DESCRIPTION
**Pull request by nayrsirhc**
The lifelong yaml indentation fight

## Type of change
fix

### What should this PR do?
Fix the indentation of the notices.yam

### Why are we making this change?
So the CI pipeline can pass

### What are the acceptance criteria? 
Successful run of the PR Checks

### How should this PR be tested?
Confirming checks are once again working

### CODE REVIEW

**Comment by nayrsirhc** [comment]
Looking much better than my previous PR [https://github.com/chainguard-dev/edu/pull/1956](https://github.com/chainguard-dev/edu/pull/1956)

**Review by smythp — APPROVED** [review]
:+1: I'll run a linter on this file next time.

**Comment by smythp** [comment]
Hey, can you let me know where this is causing issues? Thanks for the PR :)

**Comment by smythp** [comment]
OK, I see the chaos now. Strange it didn't trigger on the notice update PR.

**Comment by nayrsirhc** [comment]
Agreed I was also perplexed to see this passed before, thanks for merging

**Pull request merged**
