### PR TITLE
Fix minor path issue in command.

### PR DESCRIPTION
**Pull request by amouat**
## Type of change
Fix command in tutorial.

### What should this PR do?
Fixes apko command so it builds.

### Why are we making this change?
Tutorials should change

### What are the acceptance criteria? 
Please check the new command works

### How should this PR be tested?
Run through the tutorial steps

### CODE REVIEW

**Comment by amouat** [comment]
Note this was found by a user: https://github.com/chainguard-dev/melange/issues/902

**Review by jamonation — APPROVED** [review]
Nice catch!

**Comment by amouat** [comment]
I missed the path to the key, fixed that as well now

**Comment by amouat** [comment]
Actually there's a better way to fix this...

**Review by jamonation — APPROVED** [review]
Sounds like this is the proper fix to match the tutorial so +1

**Pull request merged**
