### PR TITLE
Adding tags to chainctl content

### PR DESCRIPTION
**Pull request by sheesh**
## Type of change
Added tags to chainctl articles. Will add tags to product tutorials in separate PR. 

### What should this PR do?
Tags should appear in chainctl articles. 

### Why are we making this change?
Implementing tags is part of the Academy V2 design plans. 

### What are the acceptance criteria? 
Tags should appear on relevant content at the top of the article. Nothing should break. 

### How should this PR be tested?
The reviewer should preview a few chainctl tutorials to make sure tags are appearing correctly.

### CODE REVIEW

**Review by ltagliaferri — COMMENTED** [review]
These are also automated docs owned by @jamonation , can you work with him to make this part of the template so the tags don't get overwritten?

**Comment by jamonation** [comment]
I think I can add them on our end of the docs pipeline with the github action that pulls them down. I'll update this branch with the change. Going to re-assign this to me if you don't object @sheesh?

**Comment by sheesh** [comment]
sounds good - thank you @jamonation !

**Comment by jamonation** [comment]
When I test this substitution locally the tags show up as expected: 
Screenshot 2023-03-21 at 3 37 49 PM

**Review by ltagliaferri — APPROVED** [review]

**Pull request merged**
