### PR TITLE
Add alpine, red hat, ubuntu compatibility pages

### PR DESCRIPTION
**Pull request by jamonation**
## Type of change
docs

### What should this PR do?
This adds Alpine, Red Hat UBI, and Ubuntu compatibility pages

### Why are we making this change?
We have the data.

### What are the acceptance criteria? 
Pages should look like the [Debian](https://edu.chainguard.dev/chainguard/chainguard-images/migration-guides/debian-compatibility/) example.

### How should this PR be tested?
[Alpine](https://deploy-preview-1391--ornate-narwhal-088216.netlify.app/chainguard/chainguard-images/migration-guides/alpine-compatibility/)
[Red Hat](https://deploy-preview-1391--ornate-narwhal-088216.netlify.app/chainguard/chainguard-images/migration-guides/red-hat-compatibility/)
[Ubuntu](https://deploy-preview-1391--ornate-narwhal-088216.netlify.app/chainguard/chainguard-images/migration-guides/ubuntu-compatibility/)

### CODE REVIEW

**Review by SharpRake — APPROVED** [review]
These look great to me!

One suggestion I have is to put these docs into their own bucket. That'll help clean up the side bar and hopefully make these all easier to find

**Comment by ltagliaferri** [comment]
I agree that we can have a Migration bucket. I think this can be even outside of the Images directory.

**Review by ltagliaferri — APPROVED** [review]
LGTM, can you add a Hugo URL redirect for the Debian page? Thank you!

**Comment by jamonation** [comment]
> LGTM, can you add a Hugo URL redirect for the Debian page? Thank you!

Ah thanks for catching that, added!

**Pull request merged**
