### PR TITLE
update gitlab identity docs to list image repos

### PR DESCRIPTION
**Pull request by imjasonh**
## Type of change

Refocus docs toward images

### What should this PR do?

Refocus GitLab assumable identity doc toward an Images use case, instead of a policy-based use case.

### Why are we making this change?

We expect users to be more interested in examples focused on images

### What are the acceptance criteria? 

The example code works as expected

### How should this PR be tested?

By creating the resources and running the GitLab workflow to show expected output.

### CODE REVIEW

**Comment by ltagliaferri** [comment]
Hi @imjasonh , where should we move this doc to, considering the focus on Images?

**Comment by imjasonh** [comment]
> Hi @imjasonh , where should we move this doc to, considering the focus on Images?

I think we should move it to some general-Admin-oriented docs area. Like docs about groups or IAM, which is shared by Enforce and Images.

**Comment by ltagliaferri** [comment]
> I think we should move it to some general-Admin-oriented docs area. Like docs about groups or IAM, which is shared by Enforce and Images.

They're currently under Enforce > Authentication > Identity Examples

We have a top-level Administration > IAM & Groups --- should we wait until all the identity examples are updated to Images and then move them up to the Admin > IAM level? Or move this for now as a standalone?

**Review by ltagliaferri — APPROVED** [review]
If it's all right, I'll merge this for now and then batch move them over when we have critical mass

**Pull request merged**
